import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useLocation, useParams, useNavigate, useSearchParams } from 'react-router-dom'
import { Archive, Paperclip, RefreshCw, Trash2 } from 'lucide-react'
import { mailApi } from '../api/mailApi'

function dateLabel(value: string) { const d = new Date(value); const today = new Date(); return d.toDateString() === today.toDateString() ? d.toLocaleTimeString('es-CL', { hour: '2-digit', minute: '2-digit' }) : d.toLocaleDateString('es-CL', { day: '2-digit', month: 'short' }) }
export function InboxPage({ folder = 'inbox' }: { folder?: string }) {
  const { accountId } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [params] = useSearchParams(); const search = params.get('q') ?? ''; const queryClient = useQueryClient(); const { data: accounts = [] } = useQuery({ queryKey: ['accounts'], queryFn: mailApi.accounts }); const { data, isLoading, isError, refetch } = useQuery({ queryKey: ['messages', accountId, folder, search], queryFn: () => mailApi.messages(accountId, folder, search), refetchInterval: 60_000, refetchIntervalInBackground: false }); const emptyTrash = useMutation({ mutationFn: () => mailApi.emptyFolder('trash', accountId), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['messages'] }); refetch() } })
  const title = search ? `Resultados para “${search}”` : accountId ? accounts.find(a => a.id === accountId)?.displayName ?? 'Cuenta' : folder === 'inbox' ? 'Bandeja de entrada' : folder === 'sent' ? 'Enviados' : folder === 'drafts' ? 'Borradores' : 'Papelera'
  const navigationItems = data?.items.map(item => ({ accountId: item.accountId, messageId: item.providerMessageId })) ?? []
  const returnTo = `${location.pathname}${location.search}`
  return <section className="mail-view"><div className="view-header"><div><p className="eyebrow">{accountId ? 'Cuenta' : 'Todas las cuentas'}</p><h1>{title}</h1></div><div className="view-actions">{folder === 'trash' && <button className="secondary-button danger-button" disabled={emptyTrash.isPending} onClick={() => { if (window.confirm('¿Vaciar permanentemente todos los correos de la Papelera?')) emptyTrash.mutate() }}><Trash2 size={16} /> {emptyTrash.isPending ? 'Vaciando…' : 'Vaciar papelera'}</button>}<button className="icon-button" onClick={() => refetch()} aria-label="Actualizar"><RefreshCw size={18} /></button></div></div>
    {(location.state as { sent?: boolean; trashed?: boolean } | null)?.sent && <div className="success-notice">Correo enviado correctamente. Ya aparece en Enviados.</div>}{(location.state as { trashed?: boolean } | null)?.trashed && <div className="success-notice">Correo movido a Papelera.</div>}{emptyTrash.isSuccess && <div className="success-notice">Papelera vaciada permanentemente.</div>}{emptyTrash.isError && <div className="notice">{emptyTrash.error instanceof Error ? emptyTrash.error.message : 'No se pudo vaciar la Papelera. Reintenta.'}</div>}{isLoading && <MailSkeleton />}{isError && <div className="notice">No se pudo actualizar una de sus cuentas. <button onClick={() => refetch()}>Reintentar</button></div>}
    {data && data.items.length === 0 && <div className="empty-state"><Archive size={28} /><h2>No hay mensajes aquí</h2><p>Los mensajes de esta carpeta aparecerán en este espacio.</p></div>}
    <div className="message-list" aria-label="Lista de mensajes">{data?.items.map(item => { const account = accounts.find(a => a.id === item.accountId); return <button key={`${item.accountId}-${item.providerMessageId}`} className={`message-row ${item.isRead ? '' : 'unread'}`} onClick={() => navigate(`/message/${item.accountId}/${item.providerMessageId}`, { state: { navigationItems, returnTo } })}><i className="account-dot" style={{ background: account?.color }} /><span className="sender">{item.senderName}</span><span className="subject"><strong>{item.subject}</strong><span> — {item.preview}</span></span>{item.hasAttachments && <Paperclip size={15} className="attachment-icon" />}<time>{dateLabel(item.receivedAt)}</time></button> })}</div>
  </section>
}
function MailSkeleton() { return <div className="message-list">{Array.from({ length: 8 }, (_, i) => <div className="skeleton-row" key={i}><span /><span /><span /></div>)}</div> }
