import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider } from 'react-router-dom'
import { ComposeValidationNotice } from './components/ComposeValidationNotice'
import { GlobalActionIndicator } from './components/GlobalActionIndicator'
import { router } from './router'
import './styles/theme.css'
import './styles/overrides.css'
import './styles/mail-enhancements.css'
import './styles/mail-actions.css'
import './styles/control-activity.css'
import './styles/control-contacts.css'
import './styles/control-documents.css'
import './styles/control-center-cleanup.css'
import './styles/unread-management.css'
import './styles/navigation-enhancements.css'
import './styles/operations-clock.css'
import './styles/dashboard-headings.css'
import './styles/inbox-loading.css'
import './styles/ai-writing.css'
import './styles/ai-inline-writing.css'
import './styles/ai-voice.css'
import './styles/compose-ai-integration.css'
import './styles/compose-cleanup.css'
import './styles/compose-validation.css'
import './styles/unified-reply-composer.css'
import './styles/message-actions.css'
import './styles/confirm-dialog.css'
import './styles/auth.css'
import './styles/auth-brand.css'
import './styles/ui-polish.css'
import './styles/attachment-preview.css'
import './styles/nexi.css'
import './styles/nexi-prompt.css'
import './styles/nexi-control-center.css'
import './styles/nexo-perspective.css'
import './styles/nexi-context-workspace.css'
import './styles/nexi-daily-brief.css'
import './styles/nexi-trends.css'
import './styles/nexi-priority.css'
import './styles/brand.css'
import './styles/landing.css'
import './styles/landing-commercial.css'
import './styles/cinematic-dark-theme.css'
import './styles/universal-search.css'
import './styles/search-context.css'
import './styles/nexi-search-actions.css'
import './styles/nexi-action-plan.css'
import './styles/search-bar.css'
import './styles/global-action-indicator.css'
import './styles/control-center-spacing.css'

const client = new QueryClient({ defaultOptions: { queries: { staleTime: 30_000, retry: 1 } } })
createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <QueryClientProvider client={client}>
      <RouterProvider router={router} />
      <ComposeValidationNotice />
      <GlobalActionIndicator />
    </QueryClientProvider>
  </StrictMode>,
)
